"""Generated files: CATALOG.md, ATTRIBUTION.md, stdlib.md, idioms.md, site data."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from snip.model import Repo, Snippet
from snip.source import markdown_summary
from snip.validate import VERSIONS

SITE = "https://fluttersmith.github.io/py-snippets"
HEADER = "<!-- Generated by `snip generate`. Do not edit by hand. -->\n\n"


def upstream_url(repo: Repo, name: str) -> str:
    up = repo.upstream
    return f"{up['repo']}/blob/{up['commit']}/snippets/{name}.md"


def _fn_list(s: Snippet) -> str:
    return ", ".join(f"`{f.name}()`" for f in s.module.functions)


def _table(rows: list[list[str]]) -> str:
    head, *body = rows
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(r) + " |" for r in body]
    return "\n".join(lines) + "\n"


def catalog(repo: Repo) -> str:
    out = [HEADER, "# Catalog\n\n"]
    out.append(
        f"{len(repo.snippets)} snippets. Every example below the functions is a "
        f"doctest, run in CI on Python {VERSIONS[0]} to {VERSIONS[-1]}.\n\n"
    )
    for cat in repo.categories:
        items = [s for s in repo.ordered() if s.meta["category"] == cat["id"]]
        if not items:
            continue
        out.append(f"## {cat['label']}\n\n{cat['blurb']}\n\n")
        rows = [["Snippet", "Functions", "Complexity"]]
        rows += [
            [
                f"[{s.meta['title']}](content/snippets/{s.slug}/index.md)",
                _fn_list(s),
                str(s.meta["complexity"]),
            ]
            for s in items
        ]
        out.append(_table(rows) + "\n")
    out.append(
        "Also: [The stdlib already does this](content/stdlib.md) · "
        "[Python idioms for JavaScript developers](content/idioms.md)\n"
    )
    return "".join(out)


def _pycon_block(text: str) -> str:
    return f"```pycon\n{text.strip()}\n```\n"


def stdlib_page(repo: Repo) -> str:
    out = [HEADER, "# The stdlib already does this\n\n"]
    out.append(
        "Before you copy a helper, check this list. Each row is a function people "
        "keep rewriting, and the standard library tool that already does it. "
        "Every example is a doctest, run in CI.\n\n"
    )
    for row in repo.stdlib:
        out.append(f"## Instead of `{row['instead']}`\n\n")
        out.append(f"Use `{row['use']}` (Python {row['since']}+).")
        if row.get("note"):
            out.append(f" {row['note']}")
        out.append("\n\n" + _pycon_block(row["example"]) + "\n")
    return "".join(out)


def idioms_page(repo: Repo) -> str:
    out = [HEADER, "# Python idioms for JavaScript developers\n\n"]
    out.append(
        "Many helpers in JavaScript snippet collections exist because arrays and "
        "objects lack something Python has built in. Here is the Python way, "
        "with an example that runs in CI.\n\n"
    )
    groups: dict[str, list[dict[str, Any]]] = {}
    for row in repo.idioms:
        groups.setdefault(str(row["group"]), []).append(row)
    for group, rows in groups.items():
        out.append(f"## {group}\n\n")
        for row in rows:
            out.append(f"### `{row['js']}` → `{row['python']}`\n\n")
            if row.get("note"):
                out.append(f"{row['note']}\n\n")
            out.append(_pycon_block(row["example"]) + "\n")
    return "".join(out)


def attribution(repo: Repo) -> str:
    up = repo.upstream

    def link(name: str) -> str:
        return f"[{name}]({upstream_url(repo, name)})"

    out = [HEADER, "# Attribution\n\n"]
    out.append(
        f"Parts of py-snippets are adapted from [30-seconds-of-python]({up['repo']}) "
        f"by the 30 seconds of code contributors, at commit "
        f"[`{up['commit'][:7]}`]({up['repo']}/tree/{up['commit']}), used under "
        "[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Every "
        "adapted page says so in its footer and lists what changed.\n\n"
        "py-snippets is an independent project. It is not affiliated with or "
        "endorsed by 30 seconds of code, and it uses none of its names, logos or "
        "images.\n\n"
        "All 160 original snippets are accounted for below. `snip validate` "
        "checks that none is missing or counted twice.\n\n"
    )
    adapted = [s for s in repo.ordered() if s.upstream]
    n_adapted = sum(len(s.upstream) for s in adapted)
    out.append(f"## Adapted as snippet pages ({n_adapted})\n\n")
    rows = [["Page", "Original", "What changed"]]
    rows += [
        [
            f"[{s.meta['title']}](content/snippets/{s.slug}/index.md)",
            ", ".join(link(n) for n in s.upstream),
            str(s.origin["change"] if s.origin else ""),
        ]
        for s in adapted
    ]
    out.append(_table(rows) + "\n")

    n_std = sum(len(r.get("upstream") or []) for r in repo.stdlib)
    out.append(f"## Replaced by the standard library ({n_std})\n\n")
    out.append("Listed on [The stdlib already does this](content/stdlib.md).\n\n")
    rows = [["Original", "Use instead"]]
    rows += [
        [", ".join(link(n) for n in r["upstream"]), f"`{r['use']}`"]
        for r in repo.stdlib
        if r.get("upstream")
    ]
    out.append(_table(rows) + "\n")

    n_id = sum(len(r.get("upstream") or []) for r in repo.idioms)
    out.append(f"## Replaced by a Python idiom ({n_id})\n\n")
    out.append(
        "These wrap something Python does natively. They're listed on "
        "[Python idioms for JavaScript developers](content/idioms.md).\n\n"
    )
    rows = [["Original", "Python idiom"]]
    rows += [
        [", ".join(link(n) for n in r["upstream"]), f"`{r['python']}`"]
        for r in repo.idioms
        if r.get("upstream")
    ]
    out.append(_table(rows) + "\n")

    planned = up.get("planned") or []
    out.append(f"## Planned for a later release ({len(planned)})\n\n")
    out.append(", ".join(link(n) for n in planned) + "\n")
    return "".join(out)


def _neighbours(items: list[Snippet], i: int) -> tuple[str | None, str | None]:
    prev = items[i - 1].slug if i > 0 else None
    nxt = items[i + 1].slug if i + 1 < len(items) else None
    return prev, nxt


def site_meta(repo: Repo) -> dict[str, Any]:
    ordered = repo.ordered()
    counts = {c["id"]: 0 for c in repo.categories}
    for s in ordered:
        counts[str(s.meta["category"])] += 1
    snippets = []
    for i, s in enumerate(ordered):
        prev, nxt = _neighbours(ordered, i)
        module = s.module
        origin = None
        if s.origin:
            origin = {
                "upstream": [
                    {"name": n, "url": upstream_url(repo, n)} for n in s.upstream
                ],
                "change": s.origin.get("change", ""),
                "kind": s.origin.get("kind", "adapted"),
            }
        snippets.append(
            {
                "slug": s.slug,
                "title": s.meta["title"],
                "summary": s.meta["summary"],
                "category": s.meta["category"],
                "tags": s.meta.get("tags") or [],
                "since": str(s.meta["since"]),
                "complexity": s.meta["complexity"],
                "stdlib": s.meta.get("stdlib"),
                "fixes": s.meta.get("fixes"),
                "published": s.published,
                "module": s.meta["module"],
                "import": "pysnippets."
                + str(s.meta["module"]).removesuffix(".py").replace("/", "."),
                "functions": [
                    {
                        "name": f.name,
                        "signature": f.signature,
                        "summary": markdown_summary(f.summary),
                    }
                    for f in module.functions
                ],
                "code": module.code,
                "examples": [
                    {"source": e.source, "want": e.want} for e in module.examples
                ],
                "origin": origin,
                "related": s.meta.get("related") or [],
                "previous": prev,
                "next": nxt,
            }
        )
    return {
        "version": _version(repo.root),
        "pythons": list(VERSIONS),
        "verifiedAt": os.environ.get("SNIP_VERIFIED_AT", ""),
        "upstream": {
            "repo": repo.upstream["repo"],
            "commit": repo.upstream["commit"],
            "total": len(repo.upstream["snippets"]),
        },
        "categories": [{**c, "count": counts[c["id"]]} for c in repo.categories],
        "tags": repo.tags,
        "snippets": snippets,
        "stdlib": [
            {
                **r,
                "upstream": [
                    {"name": n, "url": upstream_url(repo, n)}
                    for n in r.get("upstream") or []
                ],
            }
            for r in repo.stdlib
        ],
        "idioms": [
            {
                **r,
                "upstream": [
                    {"name": n, "url": upstream_url(repo, n)}
                    for n in r.get("upstream") or []
                ],
            }
            for r in repo.idioms
        ],
    }


def _version(root: Path) -> str:
    for line in (root / "pyproject.toml").read_text(encoding="utf-8").splitlines():
        if line.startswith("version ="):
            return line.split('"')[1]
    return "0.0.0"


README_START = "<!-- snip:catalog -->"
README_END = "<!-- /snip:catalog -->"


def readme_catalog(repo: Repo) -> str:
    """The README's catalog block: one collapsible list per category."""
    total, groups = len(repo.snippets), len(repo.categories)
    out = [f"\n**{total} snippets** in {groups} categories.\n\n"]
    for cat in repo.categories:
        items = [s for s in repo.ordered() if s.meta["category"] == cat["id"]]
        if not items:
            continue
        summary = f"<b>{cat['label']}</b> · {len(items)}"
        out.append(f"<details>\n<summary>{summary}</summary>\n\n")
        for s in items:
            out.append(
                f"- [{s.meta['title']}](content/snippets/{s.slug}/index.md): "
                f"{_fn_list(s)}\n"
            )
        out.append("\n</details>\n")
    return "".join(out)


def readme(repo: Repo) -> str:
    text = (repo.root / "README.md").read_text(encoding="utf-8")
    start, end = text.find(README_START), text.find(README_END)
    if start == -1 or end == -1:
        return text
    head = text[: start + len(README_START)]
    return head + "\n" + readme_catalog(repo) + text[end:]


def files(repo: Repo) -> dict[Path, str]:
    """Every generated Markdown file, keyed by path."""
    root = repo.root
    out = {
        root / "CATALOG.md": catalog(repo),
        root / "ATTRIBUTION.md": attribution(repo),
        root / "content" / "stdlib.md": stdlib_page(repo),
        root / "content" / "idioms.md": idioms_page(repo),
    }
    if (root / "README.md").is_file():
        out[root / "README.md"] = readme(repo)
    return out


def generate(repo: Repo, *, check: bool, site: bool) -> list[str]:
    """Write generated files (or with ``check``, list the stale ones)."""
    stale = []
    for path, text in files(repo).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(str(path.relative_to(repo.root)))
            if not check:
                path.write_text(text, encoding="utf-8")
    if site and not check:
        out = repo.root / "site" / "src" / "generated" / "meta.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(site_meta(repo), indent=2, ensure_ascii=False) + "\n")
    return stale
