blank_issues_enabled: false
contact_links:
  - name: Question about Python itself
    url: https://discuss.python.org/c/users/7
    about: For general Python questions, the Python forum is the best place.
